# Generated by Django 2.2.6 on 2019-12-17 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hourlyRate',
        ),
        migrations.RemoveField(
            model_name='user',
            name='img_profile',
        ),
        migrations.RemoveField(
            model_name='user',
            name='qualifications',
        ),
        migrations.RemoveField(
            model_name='user',
            name='travelPolicy',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Tutor',
        ),
    ]
