# Generated by Django 2.2.6 on 2019-12-18 00:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(blank=True, default='', max_length=500)),
                ('img_profile', models.CharField(blank=True, default='', max_length=100)),
                ('qualifications', models.CharField(blank=True, default='', max_length=500)),
                ('travelPolicy', models.CharField(blank=True, default='', max_length=500)),
                ('hourlyRate', models.CharField(blank=True, default='', max_length=100)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tutors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
