# Generated by Django 2.2.6 on 2019-12-18 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('imagefile', models.ImageField(blank=True, max_length=255, null=True, upload_to='', verbose_name='Uploaded image')),
                ('path_to_image', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
