# Generated by Django 2.2.6 on 2019-11-02 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedimage',
            old_name='imageFile',
            new_name='imagefile',
        ),
    ]
