# Generated by Django 2.2.6 on 2019-12-17 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('img', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
    ]
